# OSWorks API - Ordem de Serviços

# Listar
GET http://localhost:8080/ordens-servico

###

# Adicionar
POST http://localhost:8080/ordens-servico
Content-Type: application/json
Accept: application/json

{
  "cliente": {
    "id": 2
  },
  "descricao": "Reparo de notebook. Cliente diz que não liga.",
  "preco": 300.50
}



###

# Buscar
GET http://localhost:8080/ordens-servico/1